Lesson19_1/Lesson19_1/Models/Brand/Brand.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lesson19_1.Models.Brand
{
    public class Brand
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

Lesson19_1/Lesson19_1/Models/Brand/BrandResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lesson19_1.Models.Brand
{
    public class BrandResponse
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Lesson19_1/Lesson19_1/Models/Brand/CreateBrandRequest.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lesson19_1.Models.Brand
{
    public class CreateBrandRequest
    {
        public string Name { get; set; }

        public string Description { get; set; }
    }
}

Lesson19_1/Lesson19_1/Models/Model.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lesson19_1.Models
{
    public class Model
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int BrandDataId { get; set; }
    }
}

Lesson19_1/Lesson19_1/Models/ModelRequest.cs
using Lesson19_1.DataModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lesson19_1.Models
{
    public class ModelRequest
    {
        public string Name { get; set; }
    }
}

Lesson19_1/Lesson19_1/Models/ModelResponse.cs
using Lesson19_1.Models.Brand;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lesson19_1.Models
{
    public class ModelResponse
    {

        public int Id { get; set; }

        public string Name { get; set; }

        public BrandResponse BrandData { get; set; }
    }
}

Lesson19_1/Lesson19_1/Models/ServerResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lesson19_1.Models
{
    public class ServerResponse<T>
    {
        public T Result { get; set; }

        public bool IsSuccess { get; set; }

        public string Error { get; set; }

        public int ErrorCode { get; set; }
    }
}

Lesson19_1/Lesson19_1/Models/TestModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lesson19_1.Models
{
    public class TestModel
    {
    }
}

Lesson19_1/Lesson19_1/Models/TestRebase.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lesson19_1.Models
{
    public class TestRebase
    {
    }
}

Lesson19_1/Lesson19_1/Models/testClassOleh.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lesson19_1.Models
{
    public class testClassOleh
    {
    }
}

Lesson19_1/Lesson19_1/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lesson19_1.Models;
using Lesson19_1.Models.Brand;
using Lesson19_1.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Lesson19_1.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class BrandController : ControllerBase
    {
        //BrandController
        private IBrandService _brandService;
        private ILogger<BrandController> _logger;

        public BrandController(IBrandService brandService, ILogger<BrandController> logger)
        {
            _brandService = brandService;
            _logger = logger;
        }

        [HttpGet]
        public async Task<IEnumerable<BrandResponse>> Get()
        {
            _logger.LogInformation("Requested Get");
            return await _brandService.GetBrandsAsync();
        }

        //baseurl/brand/id
        [HttpGet("{id}")]
        public async Task<ServerResponse<Brand>> Get(int id)
        {
            var brand =  await _brandService.GetBrandAsync(id);
            if (brand == null)
            {
                return new ServerResponse<Brand> { IsSuccess = false, Error = $"Brand not found with id={id}"};
            }
            return new ServerResponse<Brand> { IsSuccess = true, Result = brand };
        }


        [HttpPost]
        public async Task  Post(CreateBrandRequest brand)
        {
            await _brandService.AddBrandAsymc(brand);
        }

        [HttpDelete]
        public async Task Delete (int id)
        {
            await _brandService.DeleteBrandAsync(id);
        }
    }
}

Lesson19_1/Lesson19_1/Controllers/BrandWebController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lesson19_1.Models.Brand;
using Lesson19_1.Services;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Lesson19_1.Controllers
{
    public class BrandWebController : Controller
    {
        private IBrandService _brandService;
        public BrandWebController(IBrandService brandService)
        {
            _brandService = brandService;
        }

        public IActionResult AddBrand()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddBrand(CreateBrandRequest brand)
        {
            await _brandService.AddBrandAsymc(brand);

            return Redirect("~/Home");
        }
    }
}

Lesson19_1/Lesson19_1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lesson19_1.Models.Brand;
using Lesson19_1.Services;
using Microsoft.AspNetCore.Mvc;

namespace Lesson19_1.Controllers
{
    public class HomeController : Controller
    {
        private readonly IBrandService _brandService;
        private readonly IModelService _modelService;

        public HomeController(IBrandService brandService, IModelService modelService)
        {
            _brandService = brandService;
            _modelService = modelService;
        }

        public async Task<IActionResult> Index()
        {
            ViewData["Description"] = "List of brands";
            ViewBag.Title = "Home";

            var brands = await _brandService.GetBrandsAsync();

            return View(brands);
        }

        public async Task<IActionResult> Models()
        {
            var models = await _modelService.GetModelsAsync();
            return View(models);
        }
    }
}

Lesson19_1/Lesson19_1/Controllers/ModelController.cs
using Lesson19_1.Models;
using Lesson19_1.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lesson19_1.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class ModelController: ControllerBase
    {
        private IModelService _modelService;

        public ModelController(IModelService modelService, ILogService logService)
        {
            _modelService = modelService;
        }

        [HttpGet]
        public Task<IList<ModelResponse>> Get()
        {
            return  _modelService.GetModelsAsync();
        }

        [HttpPost]
        public async Task Post(ModelRequest model)
        {
            await _modelService.AddModelAsync(model);
        }
    }
}

Lesson19_1/Lesson19_1/Controllers/ModelWebController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lesson19_1.Models;
using Lesson19_1.Services;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Lesson19_1.Controllers
{
    public class ModelWebController : Controller
    {
        private IModelService _modelService;

        public ModelWebController(IModelService modelService)
        {
            _modelService = modelService;
        }
        public async Task<IActionResult> ModelEdit(int id)
        {
            var models = await _modelService.GetModelsAsync();
            var m = models.FirstOrDefault(m => m.Id == id);

            return View(m);
        }

        [HttpPost] 
        public async Task<IActionResult> ModelEdit(Model model) 
        {
            await _modelService.UpdateModelAsync(model);
            return Redirect("~/Home/Models");
        }
    }
}

Lesson19_1/Lesson19_1/Views/BrandWeb/AddBrand.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>
        Add brand
    </title>
</head>
<body>
    <form method="post">
        <table>
            <tr>
                <td>Name:</td>
                <td><input type="text" name="Description"/></td>
            </tr>
            <tr>
                <td>
                    <input type="submit" value="Add brand"/>
                </td>
            </tr>
        </table>
    </form>
</body>
</html>

Lesson19_1/Lesson19_1/Views/Home/Index.cshtml
@model IList<BrandResponse>
@{ 
    ViewData["Title1"] = "Home page";
    Layout = "_Layout";
}

@section Footer{ 
    <h6>Developed by Hillel 2020</h6>
}

<!DOCTYPE html>
<html>
    <head>
        <title>
            @ViewBag.Title
        </title>
    </head>
    <body>
        <h1>@ViewData["Description"]</h1>

        @{await Html.RenderPartialAsync("_getBrands");}

    </body>
</html>

Lesson19_1/Lesson19_1/Views/Home/Models.cshtml
@using Lesson19_1.Models
@model IList<ModelResponse>
@{
    ViewData["Title"] = "Models";
    List<ModelResponse> list = new List<ModelResponse>();
}

@section Footer{
    <h6>Developed by Hillel 2020</h6>
}

<!DOCTYPE html>
<html>
<head>
    <title>
        @ViewData["Title"]
    </title>
</head>
<body>
    <table>
        <tr>
            <td>Name</td>
            <td>Model</td>
            <td><input type="button" value="Add model" onclick="location.href='AddModel'" /> </td>
        </tr>
        @foreach (var m in Model)
        {
    <tr>
        <td>@m.Name</td>
        @if (@m.BrandData != null)
        {
            <td>@m.BrandData.Name</td>
        }
        <td>
            <a asp-controller="ModelWeb" asp-action="ModelEdit" asp-route-id="@m.Id">Edit</a>
        </td>
    </tr>
        }
    </table>


</body>
</html>

Lesson19_1/Lesson19_1/Views/Home/_getBrands.cshtml
@model IList<BrandResponse>
@inject IBrandService BrandService
@{     
    IList<BrandResponse> list = await BrandService.GetBrandsAsync();
}
<h1>Brands</h1>
<a asp-controller="BrandWeb" asp-action="AddBrand">Add brand</a>
<ul>
    @foreach (var item in list)
    {
    <li>@item.Name</li>
    }
</ul>

Lesson19_1/Lesson19_1/Views/ModelWeb/ModelEdit.cshtml
@model ModelResponse
@inject IBrandService BrandService
@{ 
    IList<BrandResponse> brands = await BrandService.GetBrandsAsync();
}


<!DOCTYPE html>
<html>
<head>
    <title>
        Edit model
    </title>
    
</head>
<body>
    <form method="post">
        <table>
            <tr>
                <td>Name:</td>
                <td><input type="text" name="Name" value="@Model.Name"/></td>
            </tr>
            @Html.DropDownList("BrandDataId", new SelectList(brands,"Id", "Name"), "Select Brand")
            <tr>
                <td>
                    <input type="submit" value="Save" />
                </td>
            </tr>
        </table>
    </form>
</body>
</html>

Lesson19_1/Lesson19_1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <ul>
        <li><a href="~/Home/Index">Home</a></li>
        <li><a href="~/Home/Models">>Models</a></li>
    </ul>
    <h1>TEst layout</h1>
    <div>
        @RenderBody()
    </div>

    <footer>@RenderSection("footer", false)</footer>
</body>
</html>